(function(){function d(g,a,e){if(g===a)return 0!==g||1/g==1/a;if(null==g||null==a)return g===a;if(g.isEqual&&h5.isFunction(g.isEqual))return g.isEqual(a);if(a.isEqual&&h5.isFunction(a.isEqual))return a.isEqual(g);var b=l.call(g);if(b!=l.call(a))return!1;switch(b){case "[object String]":return g==""+a;case "[object Number]":return g!=+g?a!=+a:0==g?1/g==1/a:g==+a;case "[object Date]":case "[object Boolean]":return+g==+a;case "[object RegExp]":return g.source==a.source&&g.global==a.global&&g.multiline==
a.multiline&&g.ignoreCase==a.ignoreCase}if("object"!=typeof g||"object"!=typeof a)return!1;for(var c=e.length;c--;)if(e[c]==g)return!0;e.push(g);var c=0,q=!0;if("[object Array]"==b){if(c=g.length,q=c==a.length,q)for(;c--&&(q=c in g==c in a&&d(g[c],a[c],e)););}else{if("constructor"in g!="constructor"in a||g.constructor!=a.constructor)return!1;for(var f in g)if(h5.has(g,f)&&(c++,!(q=h5.has(a,f)&&d(g[f],a[f],e))))break;if(q){for(f in a)if(h5.has(a,f)&&!c--)break;q=!c}}return e.pop(),q}h5=function(g){return new x(g)};
var k={},h=Array.prototype,j=Object.prototype,f=h.slice,i=h.unshift,l=j.toString,n=j.hasOwnProperty,o=h.forEach,p=h.map,m=h.reduce,b=h.reduceRight,c=h.filter,r=h.every,s=h.some,v=h.indexOf,t=h.lastIndexOf,j=Array.isArray,w=Object.keys,a=Function.prototype.bind,e=h5.each=function(g,a,e){if(null!==g)if(o&&g.forEach===o)g.forEach(a,e);else if(g.length===+g.length)for(var b=0,c=g.length;b<c&&!(b in g&&a.call(e,g[b],b,g)===k);b++);else for(b in g)if(h5.has(g,b)&&a.call(e,g[b],b,g)===k)break};h5.map=function(g,
a,b){var c=[];return null===g?c:p&&g.map===p?g.map(a,b):(e(g,function(g,e,d){c[c.length]=a.call(b,g,e,d)}),g.length===+g.length&&(c.length=g.length),c)};h5.reduce=function(g,a,b,c){var d=2<arguments.length;null===g&&(g=[]);if(m&&g.reduce===m)return c&&(a=h5.bind(a,c)),d?g.reduce(a,b):g.reduce(a);e(g,function(g,e,y){d?b=a.call(c,b,g,e,y):(b=g,d=!0)});if(!d)throw new TypeError("Reduce of empty array with no initial value");return b};h5.reduceRight=function(g,a,e,c){var d=2<arguments.length;null===g&&
(g=[]);if(b&&g.reduceRight===b)return c&&(a=h5.bind(a,c)),d?g.reduceRight(a,e):g.reduceRight(a);var q=h5.toArray(g).reverse();return c&&!d&&(a=h5.bind(a,c)),d?h5.reduce(q,a,e,c):h5.reduce(q,a)};h5.find=function(g,a,e){var b;return q(g,function(g,c,d){if(a.call(e,g,c,d))return b=g,!0}),b};h5.filter=function(g,a,b){var d=[];return null===g?d:c&&g.filter===c?g.filter(a,b):(e(g,function(g,e,c){a.call(b,g,e,c)&&(d[d.length]=g)}),d)};h5.reject=function(g,a,b){var c=[];return null===g?c:(e(g,function(g,
e,d){a.call(b,g,e,d)||(c[c.length]=g)}),c)};h5.every=function(g,a,b){var c=!0;return null===g?c:r&&g.every===r?g.every(a,b):(e(g,function(g,e,d){if(!(c=c&&a.call(b,g,e,d)))return k}),!!c)};var q=h5.some=function(g,a,b){a||(a=h5.identity);var c=!1;return null===g?c:s&&g.some===s?g.some(a,b):(e(g,function(g,e,d){if(c||(c=a.call(b,g,e,d)))return k}),!!c)};h5.contains=function(g,a){var e=!1;return null===g?e:v&&g.indexOf===v?-1!==g.indexOf(a):(e=q(g,function(g){return g===a}),e)};h5.invoke=function(g,
a){var e=f.call(arguments,2);return h5.map(g,function(g){return(h5.isFunction(a)?a||g:g[a]).apply(g,e)})};h5.pluck=function(g,a){return h5.map(g,function(g){return g[a]})};h5.max=function(g,a,b){if(!a&&h5.isArray(g)&&g[0]===+g[0])return Math.max.apply(Math,g);if(!a&&h5.isEmpty(g))return-Infinity;var c={computed:-Infinity};return e(g,function(g,e,d){e=a?a.call(b,g,e,d):g;e>=c.computed&&(c={value:g,computed:e})}),c.value};h5.min=function(g,a,b){if(!a&&h5.isArray(g)&&g[0]===+g[0])return Math.min.apply(Math,
g);if(!a&&h5.isEmpty(g))return Infinity;var c={computed:Infinity};return e(g,function(g,e,d){e=a?a.call(b,g,e,d):g;e<c.computed&&(c={value:g,computed:e})}),c.value};h5.shuffle=function(g){var a=[],b;return e(g,function(g,e){b=Math.floor(Math.random()*(e+1));a[e]=a[b];a[b]=g}),a};h5.sortBy=function(g,a,e){var b=h5.isFunction(a)?a:function(g){return g[a]};return h5.pluck(h5.map(g,function(g,a,c){return{value:g,criteria:b.call(e,g,a,c)}}).sort(function(g,a){var e=g.criteria,y=a.criteria;return void 0===
e?1:void 0===y?-1:e<y?-1:e>y?1:0}),"value")};h5.groupBy=function(g,a){var b={},c=h5.isFunction(a)?a:function(g){return g[a]};return e(g,function(g,a){var e=c(g,a);(b[e]||(b[e]=[])).push(g)}),b};h5.sortedIndex=function(g,a,e){e||(e=h5.identity);for(var b=0,c=g.length;b<c;){var d=b+c>>1;e(g[d])<e(a)?b=d+1:c=d}return b};h5.toArray=function(g){return g?h5.isArray(g)?f.call(g):h5.isArguments(g)?f.call(g):g.toArray&&h5.isFunction(g.toArray)?g.toArray():h5.values(g):[]};h5.size=function(g){return h5.isArray(g)?
g.length:h5.keys(g).length};h5.first=function(g,a,e){return h5.isNumber(a)&&!e?f.call(g,0,a):g[0]};h5.initial=function(g,a,e){return f.call(g,0,g.length-(!h5.isNumber(a)||e?1:a))};h5.last=function(g,a,e){return h5.isNumber(a)&&!e?f.call(g,Math.max(g.length-a,0)):g[g.length-1]};h5.rest=function(g,a,e){return f.call(g,!h5.isNumber(a)||e?1:a)};h5.compact=function(g){return h5.filter(g,function(g){return!!g})};h5.flatten=function(g,a){return h5.reduce(g,function(g,e){return h5.isArray(e)?g.concat(a?e:
h5.flatten(e)):(g[g.length]=e,g)},[])};h5.without=function(g){return h5.difference(g,f.call(arguments,1))};h5.unique=function(g,a,e){var e=e?h5.map(g,e):g,b=[];return 3>g.length&&(a=!0),h5.reduce(e,function(e,c,d){if(a?h5.last(e)!==c||!e.length:!h5.contains(e,c))e.push(c),b.push(g[d]);return e},[]),b};h5.union=function(){return h5.unique(h5.flatten(arguments,!0))};h5.intersection=function(g){var a=f.call(arguments,1);return h5.filter(h5.unique(g),function(g){return h5.every(a,function(a){return 0<=
h5.indexOf(a,g)})})};h5.difference=function(g){var a=h5.flatten(f.call(arguments,1),!0);return h5.filter(g,function(g){return!h5.contains(a,g)})};h5.zip=function(){for(var g=f.call(arguments),a=h5.max(h5.pluck(g,"length")),e=Array(a),b=0;b<a;b++)e[b]=h5.pluck(g,""+b);return e};h5.indexOf=function(g,a,e){if(null===g)return-1;var b;if(e)return b=h5.sortedIndex(g,a),g[b]===a?b:-1;if(v&&g.indexOf===v)return g.indexOf(a);for(b=0,e=g.length;b<e;b++)if(b in g&&g[b]===a)return b;return-1};h5.lastIndexOf=
function(g,a){if(null===g)return-1;if(t&&g.lastIndexOf===t)return g.lastIndexOf(a);for(var e=g.length;e--;)if(e in g&&g[e]===a)return e;return-1};h5.range=function(g,a,e){1>=arguments.length&&(a=g||0,g=0);e=arguments[2]||1;for(var b=Math.max(Math.ceil((a-g)/e),0),c=0,d=Array(b);c<b;)d[c++]=g,g+=e;return d};var z=function(){};h5.bind=function(g,e){if(g.bind===a&&a)return a.apply(g,f.call(arguments,1));if(!h5.isFunction(g))throw new TypeError;var b=f.call(arguments,2),c=function(){if(this instanceof
c){z.prototype=g.prototype;var a=new z,d=g.apply(a,b.concat(f.call(arguments)));return Object(d)===d?d:a}return g.apply(e,b.concat(f.call(arguments)))};return c};h5.bindAll=function(a){var b=f.call(arguments,1);return 0===b.length&&(b=h5.functions(a)),e(b,function(e){a[e]=h5.bind(a[e],a)}),a};h5.memoize=function(a,e){var b={};return e||(e=h5.identity),function(){var c=e.apply(this,arguments);return h5.has(b,c)?b[c]:b[c]=a.apply(this,arguments)}};h5.delay=function(a,e){var b=f.call(arguments,2);return setTimeout(function(){return a.apply(null,
b)},e)};h5.defer=function(a){return h5.delay.apply(h5,[a,1].concat(f.call(arguments,1)))};h5.throttle=function(a,e){var b,c,d,q,f,y,h=h5.debounce(function(){f=q=!1},e);return function(){b=this;c=arguments;var i;return d||(d=setTimeout(function(){d=null;f&&a.apply(b,c);h()},e)),q?f=!0:y=a.apply(b,c),h(),q=!0,y}};h5.debounce=function(a,e,b){var c;return function(){var d=this,q=arguments;b&&!c&&a.apply(d,q);clearTimeout(c);c=setTimeout(function(){c=null;b||a.apply(d,q)},e)}};h5.once=function(a){var e=
!1,b;return function(){return e?b:(e=!0,b=a.apply(this,arguments),b)}};h5.wrap=function(a,e){return function(){var b=[a].concat(f.call(arguments,0));return e.apply(this,b)}};h5.compose=function(){var a=arguments;return function(){for(var e=arguments,b=a.length-1;0<=b;b--)e=[a[b].apply(this,e)];return e[0]}};h5.after=function(a,e){return 0>=a?e():function(){if(1>--a)return e.apply(this,arguments)}};h5.keys=w||function(a){if(a!==Object(a))throw new TypeError("Invalid object");var e=[],b;for(b in a)h5.has(a,
b)&&(e[e.length]=b);return e};h5.values=function(a){return h5.map(a,h5.identity)};h5.functions=h5.methods=function(a){var e=[],b;for(b in a)h5.isFunction(a[b])&&e.push(b);return e.sort()};h5.extend=function(a){return e(f.call(arguments,1),function(e){for(var b in e)a[b]=e[b]}),a};h5.pick=function(a){var b={};return e(h5.flatten(f.call(arguments,1)),function(e){e in a&&(b[e]=a[e])}),b};h5.defaults=function(a){return e(f.call(arguments,1),function(e){for(var b in e)h5.isUndefined(a[b])&&(a[b]=e[b])}),
a};h5.clone=function(a){return h5.isObject(a)?h5.isArray(a)?a.slice():h5.extend({},a):a};h5.tap=function(a,e){return e(a),a};h5.isEqual=function(a,e){return d(a,e,[])};h5.isEmpty=function(a){if(null===a)return!0;if(h5.isArray(a)||h5.isString(a))return 0===a.length;for(var e in a)if(h5.has(a,e))return!1;return!0};h5.isElement=function(a){return!!a&&1===a.nodeType};h5.isArray=j||function(a){return"[object Array]"===l.call(a)};h5.isObject=function(a){return a===Object(a)};h5.isArguments=function(a){return"[object Arguments]"===
l.call(a)};h5.isArguments(arguments)||(h5.isArguments=function(a){return!!a&&!!h5.has(a,"callee")});h5.isFunction=function(a){return"[object Function]"===l.call(a)};h5.isString=function(a){return"[object String]"===l.call(a)};h5.isNumber=function(a){return"[object Number]"===l.call(a)};h5.isFinite=function(a){return h5.isNumber(a)&&isFinite(a)};h5.isNaN=function(a){return a!==a};h5.isBoolean=function(a){return!0===a||!1===a||"[object Boolean]"===l.call(a)};h5.isDate=function(a){return"[object Date]"===
l.call(a)};h5.isRegExp=function(a){return"[object RegExp]"===l.call(a)};h5.isNull=function(a){return null===a};h5.isUndefined=function(a){return void 0===a};h5.has=function(a,e){return n.call(a,e)};h5.identity=function(a){return a};h5.escape=function(a){return(""+a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#x27;").replace(/\//g,"&#x2F;")};h5.global=this;var A=function(a,e,b){for(var b=b||h5.global,c=0,d;b&&(d=a[c]);c++)b=d in b?b[d]:e?b[d]=
{}:void 0;return b};h5.setObject=function(a,e,b){var c=a.split("."),a=c.pop();return(b=A(c,!0,b))&&a?b[a]=e:void 0};h5.getObject=function(a,e,b){return A(a.split("."),e,b)};h5.irand=function(a){return Math.floor(Math.random()*a)};h5.cap=function(a){return a.slice(0,1).toUpperCase()+a.slice(1)};h5.uncap=function(a){return a.slice(0,1).toLowerCase()+a.slice(1)};var B=/\{\$([^\{\}]*)\}/g;h5.macroize=function(a,e,b){var c,d,b=b||B,q=function(a,b){return d=!0,c=h5.getObject(b,!1,e),void 0===c||null===
c?"{$"+b+"}":c},f=0;do d=!1,a=a.replace(b,q);while(d&&100>f++);return a};h5.chain=function(a){return(new x(a)).chain()};h5.mixin=function(a){e(h5.functions(a),function(e){E(e,h5[e]=a[e])})};var F=0;h5.uniqueId=function(a){var e=F++;return a?a+e:e};var x=function(a){this._wrapped=a},C=function(a,e){return e?(new x(a)).chain():a},E=function(a,e){x.prototype[a]=function(){var a=f.call(arguments);return i.call(a,this._wrapped),C(e.apply(h5,a),this._chain)}};e(h5.functions(h5),function(a){E(a,h5[a])});
e("pop,push,reverse,shift,sort,splice,unshift".split(","),function(a){var e=h[a];x.prototype[a]=function(){var b=this._wrapped;e.apply(b,arguments);var c=b.length;return("shift"==a||"splice"==a)&&0===c&&delete b[0],C(b,this._chain)}});e(["concat","join","slice"],function(a){var e=h[a];x.prototype[a]=function(){return C(e.apply(this._wrapped,arguments),this._chain)}});x.prototype.chain=function(){return this._chain=!0,this};x.prototype.value=function(){return this._wrapped}}).call(this);
(function(){var d=!1;this.Class=function(){};Class.extend=function(k){var h=this.prototype;d=!0;var j=new this;d=!1;"function"==typeof k._subclass&&(j._subclasses=h._subclasses.concat(k._subclass));if(0<j._subclasses.length)for(var f=0;f<j._subclasses.length;f++)j._subclasses[f](h,j,k);for(var i in k)if(!("_super"===i||"_subclass"===i))"function"==typeof k[i]&&"function"==typeof h[i]&&(k[i]._super=h[i]),j[i]=k[i];h=function(){d||("function"==typeof this.init&&this.init.apply(this,arguments),"function"==
typeof this._inited&&this._inited.apply(this,arguments))};return h.prototype=j,h.prototype.constructor=h,h.extend=arguments.callee,h};Class.prototype._super=function(d,h){return d.callee._super.apply(this,h||d)};Class.prototype._subclasses=[]}).call(this);
(function(){h5.logging={level:99,levels:{log:20,warn:10,error:0},shouldLog:function(d){return parseInt(h5.logging.levels[d],10)<=h5.logging.level},_log:function(d,k){var h=console[d];h&&h.apply?h.apply(console,k):console.log(k)},log:function(d,k){h5.logging.shouldLog(d)&&this._log(d,k)}};h5.setLogLevel=function(d){d=parseInt(d,10);isFinite(d)&&(h5.logging.level=d)};h5.log=function(){h5.logging.log("log",arguments)};h5.warn=function(){h5.logging.log("warn",arguments)};h5.error=function(){h5.logging.log("error",
arguments)}}).call(this);
h5.Object=Class.extend({typeName:"h5.Object",getProperty:function(d){return this[d]},setProperty:function(d,k){var h="set"+h5.cap(d);this[h]?this[h](k):this._setProperty(d,k,d+"Changed")},log:function(){var d=arguments,d=[this.typeName+": "+(0<d.length?d[0]:"")].concat(h5.toArray(d).slice(1));h5.logging.log("log",d)},warn:function(){this._log("warn",arguments)},error:function(){this._log("error",arguments)},_setProperty:function(d,k,h){if(this[h]){var j=this[d];this[d]=k;j!==k&&this[h](j)}else this[d]=
k},_log:function(d,k){var h=[this.typeName+": "+(0<k.length?k[0]:"")].concat(h5.toArray(k).slice(1));h5.logging.log(d,h)},_subclass:function(d,k,h){if(d=h.published)for(var j in d)h5.Object._addGetterSetter(k,h,j,d[j]);h.typeName||(h.typeName="h5.UnnamedType")}});h5.Object._addGetterSetter=function(d,k,h,j){void 0===k[h]&&(d[h]=j);var j=h5.cap(h),f="get"+j;k[f]||(d[f]=function(){return this.getProperty(h)});var j="set"+j,i=h+"Changed";k[j]||(d[j]=function(d){this._setProperty(h,d,i)})};var ucf=ucf||{effect:{},ui:{},utils:{}};_=h5;_.any=h5.some;_.include=h5.contains;var Zepto=function(){function d(a){var e,b;if("[object Object]"!==J.call(a))return!1;b=_.isFunction(a.constructor)&&a.constructor.prototype;if(!b||!hasOwnProperty.call(b,"isPrototypeOf"))return!1;for(e in a);return e===m||hasOwnProperty.call(a,e)}function k(a){return"number"==typeof a.length}function h(a){if(String.prototype.trim)return null==a?"":String.prototype.trim.call(a);var e=/^\s+/,b=/\s+$/;return null==a?"":a.toString().replace(e,"").replace(b,"")}function j(a){return a.filter(function(a){return a!==
m&&null!==a})}function f(a){return a.replace(/::/g,"/").replace(/([A-Z]+)([A-Z][a-z])/g,"$1_$2").replace(/([a-z\d])([A-Z])/g,"$1_$2").replace(/_/g,"-").toLowerCase()}function i(e){return e in a?a[e]:a[e]=RegExp("(^|\\s)"+e+"(\\s|$)")}function l(a,e){return e===m?c(a):c(a).filter(e)}function n(a,e,b,g){return _.isFunction(e)?e.call(a,b,g):e}function o(a,e,b){var g=a%2?e:e.parentNode;g?g.insertBefore(b,!a?e.nextSibling:1==a?g.firstChild:2==a?e:null):c(b).remove()}function p(a,e){e(a);for(var b in a.childNodes)p(a.childNodes[b],
e)}var m,b,c,r,s=[],v=s.slice,t=window.document,w={},a={},e=t.defaultView.getComputedStyle,q={"column-count":1,columns:1,"font-weight":1,"line-height":1,opacity:1,"z-index":1,zoom:1},z=/^\s*<(\w+|!)[^>]*>/,A=[1,3,8,9,11],B=t.createElement("table"),F=t.createElement("tr"),x={tr:t.createElement("tbody"),tbody:B,thead:B,tfoot:B,td:F,th:F,"*":t.createElement("div")},C=/complete|loaded|interactive/,E=/^\.([\w-]+)$/,g=/^#([\w-]+)$/,I=/^[\w-]+$/,J={}.toString,u={},G,D,H=t.createElement("div");u.matches=
function(a,e){if(!a||1!==a.nodeType)return!1;var b=a.webkitMatchesSelector||a.mozMatchesSelector||a.oMatchesSelector||a.matchesSelector;if(b)return b.call(a,e);var g;g=a.parentNode;(b=!g)&&(g=H).appendChild(a);g=~u.qsa(g,e).indexOf(a);b&&H.removeChild(a);return g};G=function(a){return a.replace(/-+(.)?/g,function(a,e){return e?e.toUpperCase():""})};D=function(a){return a.filter(function(e,b){return a.indexOf(e)==b})};u.fragment=function(a,e){e===m&&(e=z.test(a)&&RegExp.$1);e in x||(e="*");var b=x[e];
b.innerHTML=""+a;return c.each(v.call(b.childNodes),function(){b.removeChild(this)})};u.Z=function(a,e){a=a||[];a.__proto__=arguments.callee.prototype;a.selector=e||"";return a};u.isZ=function(a){return a instanceof u.Z};u.init=function(a,e){if(a){if(_.isFunction(a))return c(t).ready(a);if(u.isZ(a))return a;var b;if(_.isArray(a))b=j(a);else if(d(a))b=[c.extend({},a)],a=null;else if(0<=A.indexOf(a.nodeType)||a===window)b=[a],a=null;else if(z.test(a))b=u.fragment(a.trim(),RegExp.$1),a=null;else{if(e!==
m)return c(e).find(a);b=u.qsa(t,a)}return u.Z(b,a)}return u.Z()};c=function(a,e){return u.init(a,e)};c.extend=function(a){v.call(arguments,1).forEach(function(e){for(b in e)e[b]!==m&&(a[b]=e[b])});return a};u.qsa=function(a,e){var b;return a===t&&g.test(e)?(b=a.getElementById(RegExp.$1))?[b]:s:1!==a.nodeType&&9!==a.nodeType?s:v.call(E.test(e)?a.getElementsByClassName(RegExp.$1):I.test(e)?a.getElementsByTagName(e):a.querySelectorAll(e))};c.isPlainObject=d;c.inArray=function(a,e,b){return s.indexOf.call(e,
a,b)};c.trim=function(a){return h(a)};c.uuid=0;c.map=function(a,e){var b,g=[],c;if(k(a))for(c=0;c<a.length;c++)b=e(a[c],c),null!=b&&g.push(b);else for(c in a)b=e(a[c],c),null!=b&&g.push(b);return 0<g.length?[].concat.apply([],g):g};c.each=function(a,e){var b;if(k(a))for(b=0;b<a.length&&!(!1===e.call(a[b],b,a[b]));b++);else for(b in a)if(!1===e.call(a[b],b,a[b]))break;return a};c.fn={forEach:s.forEach,reduce:s.reduce,push:s.push,indexOf:s.indexOf,concat:s.concat,map:function(a){return c.map(this,function(e,
b){return a.call(e,b,e)})},slice:function(){return c(v.apply(this,arguments))},ready:function(a){C.test(t.readyState)?a(c):t.addEventListener("DOMContentLoaded",function(){a(c)},!1);return this},get:function(a){return a===m?v.call(this):this[a]},toArray:function(){return this.get()},size:function(){return this.length},remove:function(){return this.each(function(){null!=this.parentNode&&this.parentNode.removeChild(this)})},each:function(a){this.forEach(function(e,b){a.call(e,b,e)});return this},filter:function(a){return c([].filter.call(this,
function(e){return u.matches(e,a)}))},add:function(a,e){return c(D(this.concat(c(a,e))))},is:function(a){return 0<this.length&&u.matches(this[0],a)},not:function(a){var e=[];if(_.isFunction(a)&&a.call!==m)this.each(function(b){a.call(this,b)||e.push(this)});else{var b="string"==typeof a?this.filter(a):k(a)&&_.isFunction(a.item)?v.call(a):c(a);this.forEach(function(a){0>b.indexOf(a)&&e.push(a)})}return c(e)},eq:function(a){return-1===a?this.slice(a):this.slice(a,+a+1)},first:function(){var a=this[0];
return a&&!_.isObject(a)?a:c(a)},last:function(){var a=this[this.length-1];return a&&!_.isObject(a)?a:c(a)},find:function(a){var e;e=1==this.length?u.qsa(this[0],a):this.map(function(){return u.qsa(this,a)});return c(e)},closest:function(a,e){for(var b=this[0];b&&!u.matches(b,a);)b=b!==e&&b!==t&&b.parentNode;return c(b)},parents:function(a){for(var e=[],b=this;0<b.length;)b=c.map(b,function(a){if((a=a.parentNode)&&a!==t&&0>e.indexOf(a))return e.push(a),a});return l(e,a)},parent:function(a){return l(D(this.pluck("parentNode")),
a)},children:function(a){return l(this.map(function(){return v.call(this.children)}),a)},siblings:function(a){return l(this.map(function(a,e){return v.call(e.parentNode.children).filter(function(a){return a!==e})}),a)},empty:function(){return this.each(function(){this.innerHTML=""})},pluck:function(a){return this.map(function(){return this[a]})},show:function(){return this.each(function(){"none"==this.style.display&&(this.style.display=null);if("none"==e(this,"").getPropertyValue("display")){var a=
this.style,b=this.nodeName,g,c;w[b]||(g=t.createElement(b),t.body.appendChild(g),c=e(g,"").getPropertyValue("display"),g.parentNode.removeChild(g),"none"==c&&(c="block"),w[b]=c);a.display=w[b]}})},replaceWith:function(a){return this.before(a).remove()},wrap:function(a){return this.each(function(){c(this).wrapAll(c(a)[0].cloneNode(!1))})},wrapAll:function(a){this[0]&&(c(this[0]).before(a=c(a)),a.append(this));return this},unwrap:function(){this.parent().each(function(){c(this).replaceWith(c(this).children())});
return this},clone:function(){return c(this.map(function(){return this.cloneNode(!0)}))},hide:function(){return this.css("display","none")},toggle:function(a){return(a===m?"none"==this.css("display"):a)?this.show():this.hide()},prev:function(){return c(this.pluck("previousElementSibling"))},next:function(){return c(this.pluck("nextElementSibling"))},html:function(a){return a===m?0<this.length?this[0].innerHTML:null:this.each(function(e){var b=this.innerHTML;c(this).empty().append(n(this,a,e,b))})},
text:function(a){return a===m?0<this.length?this[0].textContent:null:this.each(function(){this.textContent=a})},attr:function(a,e){var g;return"string"==typeof a&&e===m?0==this.length||1!==this[0].nodeType?m:"value"==a&&"INPUT"==this[0].nodeName?this.val():!(g=this[0].getAttribute(a))&&a in this[0]?this[0][a]:g:this.each(function(g){if(1===this.nodeType)if(_.isObject(a))for(b in a)this.setAttribute(b,a[b]);else this.setAttribute(a,n(this,e,g,this.getAttribute(a)))})},removeAttr:function(a){return this.each(function(){1===
this.nodeType&&this.removeAttribute(a)})},prop:function(a,e){return e===m?this[0]?this[0][a]:m:this.each(function(b){this[a]=n(this,e,b,this[a])})},data:function(a,e){var b=this.attr("data-"+f(a),e);return null!==b?b:m},val:function(a){return a===m?0<this.length?this[0].value:m:this.each(function(e){this.value=n(this,a,e,this.value)})},offset:function(){if(0==this.length)return null;var a=this[0].getBoundingClientRect();return{left:a.left+window.pageXOffset,top:a.top+window.pageYOffset,width:a.width,
height:a.height}},css:function(a,g){if(g===m&&"string"==typeof a)return 0==this.length?m:this[0].style[G(a)]||e(this[0],"").getPropertyValue(a);var c="";for(b in a)"string"==typeof a[b]&&""==a[b]?this.each(function(){this.style.removeProperty(f(b))}):c+=f(b)+":"+("number"==typeof a[b]&&!q[f(b)]?a[b]+"px":a[b])+";";"string"==typeof a&&(""==g?this.each(function(){this.style.removeProperty(f(a))}):c=f(a)+":"+("number"==typeof g&&!q[f(a)]?g+"px":g));return this.each(function(){this.style.cssText+=";"+
c})},index:function(a){return a?this.indexOf(c(a)[0]):this.parent().children().indexOf(this[0])},hasClass:function(a){return 1>this.length?!1:i(a).test(this[0].className)},addClass:function(a){return this.each(function(e){r=[];var b=this.className;n(this,a,e,b).split(/\s+/g).forEach(function(a){c(this).hasClass(a)||r.push(a)},this);r.length&&(this.className+=(b?" ":"")+r.join(" "))})},removeClass:function(a){return this.each(function(e){if(a===m)return this.className="";r=this.className;n(this,a,
e,r).split(/\s+/g).forEach(function(a){r=r.replace(i(a)," ")});if(null!=r)this.className=h(r)})},toggleClass:function(a,e){return this.each(function(b){b=n(this,a,b,this.className);(e===m?!c(this).hasClass(b):e)?c(this).addClass(b):c(this).removeClass(b)})}};["width","height"].forEach(function(a){c.fn[a]=function(e){var b,g=a.replace(/./,function(a){return a[0].toUpperCase()}),d=window.getComputedStyle?window.getComputedStyle(this[0],null):null;return e===m?this[0]==window?window["inner"+g]:this[0]==
t?t.documentElement["offset"+g]:d?d[a]:(b=this.offset())&&b[a]:this.each(function(b){var g=c(this);g.css(a,n(this,e,b,g[a]()))})}});["after","prepend","before","append"].forEach(function(a,e){c.fn[a]=function(){var a=c.map(arguments,function(a){return _.isObject(a)?a:u.fragment(a)});if(1>a.length)return this;var b=this.length,g=1<b,d=2>e;return this.each(function(c,q){for(var f=0;f<a.length;f++){var h=a[d?a.length-f-1:f];p(h,function(a){null!=a.nodeName&&"SCRIPT"===a.nodeName.toUpperCase()&&(!a.type||
"text/javascript"===a.type)&&window.eval.call(window,a.innerHTML)});g&&c<b-1&&(h=h.cloneNode(!0));o(e,q,h)}})};c.fn[e%2?a+"To":"insert"+(e?"Before":"After")]=function(e){c(e)[a](this);return this}});u.Z.prototype=c.fn;u.camelize=G;u.uniq=D;c.zepto=u;return c}();window.Zepto=Zepto;"$"in window||(window.$=Zepto);
(function(d){function k(b){return b._zid||(b._zid=m++)}function h(b,c,d,a){c=j(c);if(c.ns)var e=RegExp("(?:^| )"+c.ns.replace(" "," .* ?")+"(?: |$)");return(p[k(b)]||[]).filter(function(b){return b&&(!c.e||b.e==c.e)&&(!c.ns||e.test(b.ns))&&(!d||k(b.fn)===k(d))&&(!a||b.sel==a)})}function j(b){b=(""+b).split(".");return{e:b[0],ns:b.slice(1).sort().join(" ")}}function f(b,c,f){_.isObject(b)?d.each(b,f):b.split(/\s/).forEach(function(a){f(a,c)})}function i(b,c,h,a,e,q){var q=!!q,i=k(b),l=p[i]||(p[i]=
[]);f(c,h,function(c,f){var h=e&&e(f,c),i=h||f,k=function(a){var e=i.apply(b,[a].concat(a.data));!1===e&&a.preventDefault();return e},h=d.extend(j(c),{fn:f,proxy:k,sel:a,del:h,i:l.length});l.push(h);b.addEventListener(h.e,k,q)})}function l(b,c,d,a){var e=k(b);f(c||"",d,function(c,d){h(b,c,d,a).forEach(function(a){delete p[e][a.i];b.removeEventListener(a.e,a.proxy,!1)})})}function n(b){var f=d.extend({originalEvent:b},b);d.each(s,function(d,a){f[d]=function(){this[a]=c;return b[d].apply(b,arguments)};
f[a]=r});return f}function o(b){if(!("defaultPrevented"in b)){b.defaultPrevented=!1;var c=b.preventDefault;b.preventDefault=function(){this.defaultPrevented=!0;c.call(this)}}}var p={},m=1,b={};b.click=b.mousedown=b.mouseup=b.mousemove="MouseEvents";d.event={add:i,remove:l};d.proxy=function(b,c){if(_.isFunction(b)){var f=function(){return b.apply(c,arguments)};f._zid=k(b);return f}if("string"==typeof c)return d.proxy(b[c],b);throw new TypeError("expected function");};d.fn.bind=function(b,c){return this.each(function(){i(this,
b,c)})};d.fn.unbind=function(b,c){return this.each(function(){l(this,b,c)})};d.fn.one=function(b,c){return this.each(function(d,a){i(this,b,c,null,function(e,b){return function(){var c=e.apply(a,arguments);l(a,b,e);return c}})})};var c=function(){return!0},r=function(){return!1},s={preventDefault:"isDefaultPrevented",stopImmediatePropagation:"isImmediatePropagationStopped",stopPropagation:"isPropagationStopped"};d.fn.delegate=function(b,c,f){var a=!1;if("blur"==c||"focus"==c)d.iswebkit?c="blur"==
c?"focusout":"focus"==c?"focusin":c:a=!0;return this.each(function(e,q){i(q,c,f,b,function(a){return function(e){var c,f=d(e.target).closest(b,q).get(0);if(f)return c=d.extend(n(e),{currentTarget:f,liveFired:q}),a.apply(f,[c].concat([].slice.call(arguments,1)))}},a)})};d.fn.undelegate=function(b,c,d){return this.each(function(){l(this,c,d,b)})};d.fn.live=function(b,c){d(document.body).delegate(this.selector,b,c);return this};d.fn.die=function(b,c){d(document.body).undelegate(this.selector,b,c);return this};
d.fn.on=function(b,c,d){return void 0==c||_.isFunction(c)?this.bind(b,c):this.delegate(c,b,d)};d.fn.off=function(b,c,d){return void 0==c||_.isFunction(c)?this.unbind(b,c):this.undelegate(c,b,d)};d.fn.trigger=function(b,c){"string"==typeof b&&(b=d.Event(b));o(b);b.data=c;return this.each(function(){"dispatchEvent"in this&&this.dispatchEvent(b)})};d.fn.triggerHandler=function(b,c){var f,a;this.each(function(e,q){f=n("string"==typeof b?d.Event(b):b);f.data=c;f.target=q;d.each(h(q,b.type||b),function(b,
e){a=e.proxy(f);if(f.isImmediatePropagationStopped())return!1})});return a};"focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout change select keydown keypress keyup error".split(" ").forEach(function(b){d.fn[b]=function(c){return this.bind(b,c)}});["focus","blur"].forEach(function(b){d.fn[b]=function(c){if(c)this.bind(b,c);else if(this.length)try{this.get(0)[b]()}catch(d){}return this}});d.Event=function(c,d){var f=document.createEvent(b[c]||"Events"),
a=!0;if(d)for(var e in d)"bubbles"==e?a=!!d[e]:f[e]=d[e];f.initEvent(c,a,!0,null,null,null,null,null,null,null,null,null,null,null,null);return f}})(Zepto);
(function(d,k){var h="",j,f=window.document.createElement("div"),i=/^((translate|rotate|scale)(X|Y|Z|3d)?|matrix(3d)?|perspective|skew(X|Y)?)$/i,l={};d.each({Webkit:"webkit",Moz:"",O:"o",ms:"MS"},function(d,i){if(f.style[d+"TransitionProperty"]!==k)return h="-"+d.toLowerCase()+"-",j=i,!1});l[h+"transition-property"]=l[h+"transition-duration"]=l[h+"transition-timing-function"]=l[h+"animation-name"]=l[h+"animation-duration"]="";d.fx={off:j===k&&f.style.transitionProperty===k,cssPrefix:h,transitionEnd:j?
j+"TransitionEnd":"transitionend",animationEnd:j?j+"AnimationEnd":"animationend"};d.fn.animate=function(d,f,h,i){if(_.isObject(f))h=f.easing,i=f.complete,f=f.duration;f&&(f/=1E3);return this.anim(d,f,h,i)};d.fn.anim=function(f,j,p,m){var b,c={},r,s=this,v,t=d.fx.transitionEnd;j===k&&(j=0.4);d.fx.off&&(j=0);if("string"==typeof f)c[h+"animation-name"]=f,c[h+"animation-duration"]=j+"s",t=d.fx.animationEnd;else{for(r in f)i.test(r)?(b||(b=[]),b.push(r+"("+f[r]+")")):c[r]=f[r];b&&(c[h+"transform"]=b.join(" "));
!d.fx.off&&"object"===typeof f&&(c[h+"transition-property"]=(Object.keys?Object.keys:function(b){if(b!==Object(b))throw new TypeError("Invalid object");var a=[],e;for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(a[a.length]=e);return a})(f).join(", "),c[h+"transition-duration"]=j+"s",c[h+"transition-timing-function"]=p||"linear")}v=function(b){if("undefined"!==typeof b){if(b.target!==b.currentTarget)return;d(b.target).unbind(t,arguments.callee)}d(this).css(l);m&&m.call(this)};setTimeout(function(){s.css(c);
setTimeout(function(){s.each(function(){v.call(this)})},1E3*j)},0);return this};f=null})(Zepto);
(function(d){function k(a,b,e,c){if(a.global)return a=b||r,e=d.Event(e),d(a).trigger(e,c),!e.defaultPrevented}function h(a){a.global&&0===d.active++&&k(a,null,"ajaxStart")}function j(a,b){var e=b.context;if(!1===b.beforeSend.call(e,a,b)||!1===k(b,e,"ajaxBeforeSend",[a,b]))return!1;k(b,e,"ajaxSend",[a,b])}function f(a,b,e){var c=e.context;e.success.call(c,a,"success",b);k(e,c,"ajaxSuccess",[b,e,a]);l("success",b,e)}function i(a,b,e,c){var d=c.context;c.error.call(d,e,b,a);k(c,d,"ajaxError",[e,c,a]);
l(b,e,c)}function l(a,b,e){var c=e.context;e.complete.call(c,b,a);k(e,c,"ajaxComplete",[b,e]);e.global&&!--d.active&&k(e,null,"ajaxStop")}function n(){}function o(b){return b&&(b==q?"html":b==e?"json":w.test(b)?"script":a.test(b)&&"xml")||"text"}function p(a){if(c(a.data))a.data=d.param(a.data);if(a.data&&(!a.type||"GET"==a.type.toUpperCase()))a.url=(a.url+"&"+a.data).replace(/[&?]{1,2}/,"?")}function m(a,b,e,f){var q=_.isArray(b);d.each(b,function(b,h){f&&(b=e?f:f+"["+(q?"":b)+"]");!f&&q?a.add(h.name,
h.value):(e?d.isArray(h):c(h))?m(a,h,e,b):a.add(b,h)})}var b=0,c=_.isObject,r=window.document,s,v,t=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,w=/^(?:text|application)\/javascript/i,a=/^(?:text|application)\/xml/i,e="application/json",q="text/html",z=/^\s*$/;d.active=0;d.ajaxJSONP=function(a){var e="jsonp"+ ++b,c=r.createElement("script"),q={abort:function(){d(c).remove();e in window&&(window[e]=n);l("abort",q,a)}},h;if(a.error)c.onerror=function(){q.abort();a.error()};window[e]=function(b){clearTimeout(h);
d(c).remove();delete window[e];f(b,q,a)};p(a);c.src=a.url.replace(/=\?/,"="+e);d("head").append(c);0<a.timeout&&(h=setTimeout(function(){q.abort();l("timeout",q,a)},a.timeout));return q};d.ajaxSettings={type:"GET",beforeSend:n,success:n,error:n,complete:n,context:null,global:!0,xhr:function(){return new window.XMLHttpRequest},accepts:{script:"text/javascript, application/javascript",json:e,xml:"application/xml, text/xml",html:q,text:"text/plain"},crossDomain:!1,timeout:0};d.ajax=function(a){var b=
d.extend({},a||{});for(s in d.ajaxSettings)void 0===b[s]&&(b[s]=d.ajaxSettings[s]);h(b);if(!b.crossDomain)b.crossDomain=/^([\w-]+:)?\/\/([^\/]+)/.test(b.url)&&RegExp.$2!=window.location.host;var e=b.dataType,a=/=\?/.test(b.url);if("jsonp"==e||a){if(!a)b.url=(b.url+"&callback=?").replace(/[&?]{1,2}/,"?");return d.ajaxJSONP(b)}if(!b.url)b.url=window.location.toString();p(b);var a=b.accepts[e],c={},q=/^([\w-]+:)\/\//.test(b.url)?RegExp.$1:window.location.protocol,g=d.ajaxSettings.xhr(),k;b.crossDomain||
(c["X-Requested-With"]="XMLHttpRequest");if(a)c.Accept=a,-1<a.indexOf(",")&&(a=a.split(",",2)[0]),g.overrideMimeType&&g.overrideMimeType(a);if(b.contentType||b.data&&"GET"!=b.type.toUpperCase())c["Content-Type"]=b.contentType||"application/x-www-form-urlencoded";b.headers=d.extend(c,b.headers||{});g.onreadystatechange=function(){if(4==g.readyState){clearTimeout(k);var a,c=!1;if(200<=g.status&&300>g.status||304==g.status||0==g.status&&"file:"==q){e=e||o(g.getResponseHeader("content-type"));a=g.responseText;
try{"script"==e?(0,eval)(a):"xml"==e?a=g.responseXML:"json"==e&&(a=z.test(a)?null:JSON.parse(a))}catch(d){c=d}c?i(c,"parsererror",g,b):f(a,g,b)}else i(null,"error",g,b)}};g.open(b.type,b.url,"async"in b?b.async:!0);for(v in b.headers)g.setRequestHeader(v,b.headers[v]);if(!1===j(g,b))return g.abort(),!1;0<b.timeout&&(k=setTimeout(function(){g.onreadystatechange=n;g.abort();i(null,"timeout",g,b)},b.timeout));g.send(b.data?b.data:null);return g};d.get=function(a,b){return d.ajax({url:a,success:b})};
d.post=function(a,b,e,c){d.isFunction(b)&&(c=c||e,e=b,b=null);return d.ajax({type:"POST",url:a,data:b,success:e,dataType:c})};d.getJSON=function(a,b){return d.ajax({url:a,success:b,dataType:"json"})};d.fn.load=function(a,b){if(!this.length)return this;var e=this,c=a.split(/\s/),f;1<c.length&&(a=c[0],f=c[1]);d.get(a,function(a){e.html(f?d(r.createElement("div")).html(a.replace(t,"")).find(f).html():a);b&&b.call(e)});return this};var A=encodeURIComponent;d.param=function(a,b){var e=[];e.add=function(a,
b){this.push(A(a)+"="+A(b))};m(e,a,b);return e.join("&").replace("%20","+")}})(Zepto);
(function(d){d.fn.serializeArray=function(){var k=[],h;d(Array.prototype.slice.call(this.get(0).elements)).each(function(){h=d(this);var j=h.attr("type");"fieldset"!=this.nodeName.toLowerCase()&&!this.disabled&&"submit"!=j&&"reset"!=j&&"button"!=j&&("radio"!=j&&"checkbox"!=j||this.checked)&&k.push({name:h.attr("name"),value:h.val()})});return k};d.fn.serialize=function(){var d=[];this.serializeArray().forEach(function(h){d.push(encodeURIComponent(h.name)+"="+encodeURIComponent(h.value))});return d.join("&")};
d.fn.submit=function(k){k?this.bind("submit",k):this.length&&(k=d.Event("submit"),this.eq(0).trigger(k),k.defaultPrevented||this.get(0).submit());return this}})(Zepto);
(function(d){_.each(["fadeIn","fadeOut","slideUp","slideDown"],function(h){d.fn[h]=function(j,f){var i=k(j),l=this,n,f=!_.isUndefined(f)&&_.isFunction(f)?f:null;switch(h){case "fadeIn":!_.isUndefined(n=l.css("opacity"))||(n=1);l.css({display:"",opacity:"0"});l.animate({opacity:n},i,"linear",function(){l.css({display:"",opacity:n});f&&f.apply()});break;case "fadeOut":l.animate({opacity:"0"},i,"linear",function(){l.css({display:"none",opacity:""});f&&f.apply()});break;case "slideUp":l.css("overflow",
"hidden");l.animate({height:"0",marginTop:"0",marginBottom:"0",paddingTop:"0",paddingBottom:"0"},i,"linear",function(){l.css({height:"",marginTop:"",marginBottom:"",paddingTop:"",paddingBottom:"",display:"none",overflow:""});f&&f.apply()});break;case "slideDown":var o=document.createElement("div"),p=["height","marginTop","marginBottom","paddingTop","paddingBottom"],m={},b=l.clone();b.show();d(o).append(b);d("body").append(o);_.each(p,function(b){m[b]=parseInt(d(o).find(":first-child").css(b));(isNaN(m[b])||
0===m[b])&&delete m[b];d(o).find(":first-child").css(b,0)});d(o).remove();l.show();l.css({height:"0px",marginTop:"0px",marginBottom:"0px",paddingTop:"0px",paddingBottom:"0px",overflow:"hidden"});l.animate(m,i,"linear",function(){_.each(p,function(b){m[b]=""});m.overflow="";l.css(m);f&&f.apply()})}}});var k=function(d){var j=400;"fast"==d?j=200:"slow"==d?j=600:d&&"number"==typeof d&&(j=d);return j}})(Zepto);(function(){var d=this,k=d.Backbone,h=Array.prototype.slice,j=Array.prototype.splice,f;f="undefined"!==typeof exports?exports:d.Backbone={};f.VERSION="0.9.2";var i=d._;!i&&"undefined"!==typeof require&&(i=require("underscore"));var l=d.jQuery||d.Zepto||d.ender;f.setDomLibrary=function(a){l=a};f.noConflict=function(){d.Backbone=k;return this};f.emulateHTTP=!1;f.emulateJSON=!1;var n=/\s+/,o=f.Events={on:function(a,b,c){var d,f,h,i,j;if(!b)return this;a=a.split(n);for(d=this._callbacks||(this._callbacks=
{});f=a.shift();)h=(j=d[f])?j.tail:{},h.next=i={},h.context=c,h.callback=b,d[f]={tail:i,next:j?j.next:h};return this},off:function(a,b,c){var d,f,h,j,k,l;if(f=this._callbacks){if(!a&&!b&&!c)return delete this._callbacks,this;for(a=a?a.split(n):i.keys(f);d=a.shift();)if(h=f[d],delete f[d],h&&(b||c))for(j=h.tail;(h=h.next)!==j;)if(k=h.callback,l=h.context,b&&k!==b||c&&l!==c)this.on(d,k,l);return this}},trigger:function(a){var b,c,d,f,i,j;if(!(d=this._callbacks))return this;i=d.all;a=a.split(n);for(j=
h.call(arguments,1);b=a.shift();){if(c=d[b])for(f=c.tail;(c=c.next)!==f;)c.callback.apply(c.context||this,j);if(c=i){f=c.tail;for(b=[b].concat(j);(c=c.next)!==f;)c.callback.apply(c.context||this,b)}}return this}};o.bind=o.on;o.unbind=o.off;var p=f.Model=function(a,b){var c;a||(a={});b&&b.parse&&(a=this.parse(a));if(c=w(this,"defaults"))a=i.extend({},c,a);if(b&&b.collection)this.collection=b.collection;this.attributes={};this._escapedAttributes={};this.cid=i.uniqueId("c");this.changed={};this._silent=
{};this._pending={};this.set(a,{silent:!0});this.changed={};this._silent={};this._pending={};this._previousAttributes=i.clone(this.attributes);this.initialize.apply(this,arguments)};i.extend(p.prototype,o,{changed:null,_silent:null,_pending:null,idAttribute:"id",initialize:function(){},toJSON:function(){return i.clone(this.attributes)},get:function(a){return this.attributes[a]},escape:function(a){var b;if(b=this._escapedAttributes[a])return b;b=this.get(a);return this._escapedAttributes[a]=i.escape(null==
b?"":""+b)},has:function(a){return null!=this.get(a)},set:function(a,b,c){var d,f;i.isObject(a)||null==a?(d=a,c=b):(d={},d[a]=b);c||(c={});if(!d)return this;if(d instanceof p)d=d.attributes;if(c.unset)for(f in d)d[f]=void 0;if(!this._validate(d,c))return!1;if(this.idAttribute in d)this.id=d[this.idAttribute];var b=c.changes={},h=this.attributes,j=this._escapedAttributes,k=this._previousAttributes||{};for(f in d){a=d[f];if(!i.isEqual(h[f],a)||c.unset&&i.has(h,f))delete j[f],(c.silent?this._silent:
b)[f]=!0;c.unset?delete h[f]:h[f]=a;!i.isEqual(k[f],a)||i.has(h,f)!=i.has(k,f)?(this.changed[f]=a,c.silent||(this._pending[f]=!0)):(delete this.changed[f],delete this._pending[f])}c.silent||this.change(c);return this},unset:function(a,b){(b||(b={})).unset=!0;return this.set(a,null,b)},clear:function(a){(a||(a={})).unset=!0;return this.set(i.clone(this.attributes),a)},fetch:function(a){var a=a?i.clone(a):{},b=this,c=a.success;a.success=function(d,f,h){if(!b.set(b.parse(d,h),a))return!1;c&&c(b,d)};
a.error=f.wrapError(a.error,b,a);return(this.sync||f.sync).call(this,"read",this,a)},save:function(a,b,c){var d,h;i.isObject(a)||null==a?(d=a,c=b):(d={},d[a]=b);c=c?i.clone(c):{};if(c.wait){if(!this._validate(d,c))return!1;h=i.clone(this.attributes)}a=i.extend({},c,{silent:!0});if(d&&!this.set(d,c.wait?a:c))return!1;var j=this,k=c.success;c.success=function(a,b,e){b=j.parse(a,e);c.wait&&(delete c.wait,b=i.extend(d||{},b));if(!j.set(b,c))return!1;k?k(j,a):j.trigger("sync",j,a,c)};c.error=f.wrapError(c.error,
j,c);b=this.isNew()?"create":"update";b=(this.sync||f.sync).call(this,b,this,c);c.wait&&this.set(h,a);return b},destroy:function(a){var a=a?i.clone(a):{},b=this,c=a.success,d=function(){b.trigger("destroy",b,b.collection,a)};if(this.isNew())return d(),!1;a.success=function(f){a.wait&&d();c?c(b,f):b.trigger("sync",b,f,a)};a.error=f.wrapError(a.error,b,a);var h=(this.sync||f.sync).call(this,"delete",this,a);a.wait||d();return h},url:function(){var a;if(!(a=w(this,"urlRoot")))if(!(a=w(this.collection,
"url")))throw Error('A "url" property or function must be specified');return this.isNew()?a:a+("/"==a.charAt(a.length-1)?"":"/")+encodeURIComponent(this.id)},parse:function(a){return a},clone:function(){return new this.constructor(this.attributes)},isNew:function(){return null==this.id},change:function(a){a||(a={});var b=this._changing;this._changing=!0;for(var c in this._silent)this._pending[c]=!0;var d=i.extend({},a.changes,this._silent);this._silent={};for(c in d)this.trigger("change:"+c,this,
this.get(c),a);if(b)return this;for(;!i.isEmpty(this._pending);){this._pending={};this.trigger("change",this,a);for(c in this.changed)!this._pending[c]&&!this._silent[c]&&delete this.changed[c];this._previousAttributes=i.clone(this.attributes)}this._changing=!1;return this},hasChanged:function(a){return!arguments.length?!i.isEmpty(this.changed):i.has(this.changed,a)},changedAttributes:function(a){if(!a)return this.hasChanged()?i.clone(this.changed):!1;var b,c=!1,d=this._previousAttributes,f;for(f in a)if(!i.isEqual(d[f],
b=a[f]))(c||(c={}))[f]=b;return c},previous:function(a){return!arguments.length||!this._previousAttributes?null:this._previousAttributes[a]},previousAttributes:function(){return i.clone(this._previousAttributes)},isValid:function(){return!this.validate(this.attributes)},_validate:function(a,b){if(b.silent||!this.validate)return!0;var a=i.extend({},this.attributes,a),c=this.validate(a,b);if(!c)return!0;b&&b.error?b.error(this,c,b):this.trigger("error",this,c,b);return!1}});var m=f.Collection=function(a,
b){b||(b={});if(b.model)this.model=b.model;if(b.comparator)this.comparator=b.comparator;this._reset();this.initialize.apply(this,arguments);a&&this.reset(a,{silent:!0,parse:b.parse})};i.extend(m.prototype,o,{model:p,initialize:function(){},toJSON:function(a){return this.map(function(b){return b.toJSON(a)})},add:function(a,b){var c,d,f,h,k,l={},r={},n=[];b||(b={});a=i.isArray(a)?a.slice():[a];for(c=0,d=a.length;c<d;c++){if(!(f=a[c]=this._prepareModel(a[c],b)))throw Error("Can't add an invalid model to a collection");
h=f.cid;k=f.id;l[h]||this._byCid[h]||null!=k&&(r[k]||this._byId[k])?n.push(c):l[h]=r[k]=f}for(c=n.length;c--;)a.splice(n[c],1);for(c=0,d=a.length;c<d;c++)(f=a[c]).on("all",this._onModelEvent,this),this._byCid[f.cid]=f,null!=f.id&&(this._byId[f.id]=f);this.length+=d;j.apply(this.models,[null!=b.at?b.at:this.models.length,0].concat(a));this.comparator&&this.sort({silent:!0});if(b.silent)return this;for(c=0,d=this.models.length;c<d;c++)if(l[(f=this.models[c]).cid])b.index=c,f.trigger("add",f,this,b);
return this},remove:function(a,b){var c,d,f,h;b||(b={});a=i.isArray(a)?a.slice():[a];for(c=0,d=a.length;c<d;c++)if(h=this.getByCid(a[c])||this.get(a[c])){delete this._byId[h.id];delete this._byCid[h.cid];f=this.indexOf(h);this.models.splice(f,1);this.length--;if(!b.silent)b.index=f,h.trigger("remove",h,this,b);this._removeReference(h)}return this},push:function(a,b){a=this._prepareModel(a,b);this.add(a,b);return a},pop:function(a){var b=this.at(this.length-1);this.remove(b,a);return b},unshift:function(a,
b){a=this._prepareModel(a,b);this.add(a,i.extend({at:0},b));return a},shift:function(a){var b=this.at(0);this.remove(b,a);return b},get:function(a){return null==a?void 0:this._byId[null!=a.id?a.id:a]},getByCid:function(a){return a&&this._byCid[a.cid||a]},at:function(a){return this.models[a]},where:function(a){return i.isEmpty(a)?[]:this.filter(function(b){for(var c in a)if(a[c]!==b.get(c))return!1;return!0})},sort:function(a){a||(a={});if(!this.comparator)throw Error("Cannot sort a set without a comparator");
var b=i.bind(this.comparator,this);1==this.comparator.length?this.models=this.sortBy(b):this.models.sort(b);a.silent||this.trigger("reset",this,a);return this},pluck:function(a){return i.map(this.models,function(b){return b.get(a)})},reset:function(a,b){a||(a=[]);b||(b={});for(var c=0,d=this.models.length;c<d;c++)this._removeReference(this.models[c]);this._reset();this.add(a,i.extend({silent:!0},b));b.silent||this.trigger("reset",this,b);return this},fetch:function(a){a=a?i.clone(a):{};if(void 0===
a.parse)a.parse=!0;var b=this,c=a.success;a.success=function(d,f,h){b[a.add?"add":"reset"](b.parse(d,h),a);c&&c(b,d)};a.error=f.wrapError(a.error,b,a);return(this.sync||f.sync).call(this,"read",this,a)},create:function(a,b){var c=this,b=b?i.clone(b):{},a=this._prepareModel(a,b);if(!a)return!1;b.wait||c.add(a,b);var d=b.success;b.success=function(f,h){b.wait&&c.add(f,b);d?d(f,h):f.trigger("sync",a,h,b)};a.save(null,b);return a},parse:function(a){return a},chain:function(){return i(this.models).chain()},
_reset:function(){this.length=0;this.models=[];this._byId={};this._byCid={}},_prepareModel:function(a,b){b||(b={});if(a instanceof p){if(!a.collection)a.collection=this}else{var c;b.collection=this;a=new this.model(a,b);a._validate(a.attributes,b)||(a=!1)}return a},_removeReference:function(a){this==a.collection&&delete a.collection;a.off("all",this._onModelEvent,this)},_onModelEvent:function(a,b,c,d){("add"==a||"remove"==a)&&c!=this||("destroy"==a&&this.remove(b,d),b&&a==="change:"+b.idAttribute&&
(delete this._byId[b.previous(b.idAttribute)],this._byId[b.id]=b),this.trigger.apply(this,arguments))}});i.each([,"each","map","reduce","reduceRight","find",,"filter",,"reject","every",,"some",,,"contains","invoke","max","min","sortBy","sortedIndex","toArray","size","first","initial","rest","last","without","indexOf","shuffle","lastIndexOf","isEmpty","groupBy"],function(a){m.prototype[a]=function(){return i[a].apply(i,[this.models].concat(i.toArray(arguments)))}});var b=f.View=function(a){this.cid=
i.uniqueId("view");this._configure(a||{});this._ensureElement();this.initialize.apply(this,arguments);this.delegateEvents()},c=/^(\S+)\s*(.*)$/,r="model,collection,el,id,attributes,className,tagName".split(",");i.extend(b.prototype,o,{tagName:"div",$:function(a){return this.$el.find(a)},initialize:function(){},render:function(){return this},remove:function(){this.$el.remove();return this},make:function(a,b,c){a=document.createElement(a);b&&l(a).attr(b);c&&l(a).html(c);return a},setElement:function(a,
b){this.$el&&this.undelegateEvents();this.$el=a instanceof l?a:l(a);this.el=this.$el[0];!1!==b&&this.delegateEvents();return this},delegateEvents:function(a){if(a||(a=w(this,"events"))){this.undelegateEvents();for(var b in a){var d=a[b];i.isFunction(d)||(d=this[a[b]]);if(!d)throw Error('Method "'+a[b]+'" does not exist');var f=b.match(c),h=f[1],f=f[2],d=i.bind(d,this),h=h+(".delegateEvents"+this.cid);""===f?this.$el.bind(h,d):this.$el.delegate(f,h,d)}}},undelegateEvents:function(){this.$el.unbind(".delegateEvents"+
this.cid)},_configure:function(a){this.options&&(a=i.extend({},this.options,a));for(var b=0,c=r.length;b<c;b++){var d=r[b];a[d]&&(this[d]=a[d])}this.options=a},_ensureElement:function(){if(this.el)this.setElement(this.el,!1);else{var a=w(this,"attributes")||{};if(this.id)a.id=this.id;if(this.className)a["class"]=this.className;this.setElement(this.make(this.tagName,a),!1)}}});var s=f.Controller=function(){i.bindAll(this);this.initialize.apply(this,arguments)};i.extend(s.prototype,o,{model:p,collection:m,
initialize:function(){},callBackMix:function(a,b,c){var d={},c=!i.isUndefined(c)?c:!1;d.success=a?a:null;d.error=b?b:c&&d.success?d.success:null;return d}});p.extend=m.extend=s.extend=b.extend=function(a,b){var c=t(this,a,b);c.extend=this.extend;return c};f.wrapError=function(a,b,c){return function(d,f){f=d===b?f:d;a?a(b,f,c):b.trigger("error",b,f,c)}};var v=function(){},t=function(a,b,c){var d;d=b&&b.hasOwnProperty("constructor")?b.constructor:function(){a.apply(this,arguments)};i.extend(d,a);v.prototype=
a.prototype;d.prototype=new v;b&&i.extend(d.prototype,b);c&&i.extend(d,c);d.prototype.constructor=d;d.__super__=a.prototype;return d},w=function(a,b){return!a||!a[b]?null:i.isFunction(a[b])?a[b]():a[b]}}).call(this);(function(){function d(b,c){var d;this.element="object"==typeof b?b:document.getElementById(b);this.wrapper=this.element.parentNode;this.element.style.webkitTransitionProperty="-webkit-transform";this.element.style.webkitTransitionTimingFunction="cubic-bezier(0,0,0.25,1)";this.element.style.webkitTransitionDuration="0";this.element.style.webkitTransform=o+"0,0"+p;this.options={bounce:h,momentum:h,checkDOMChanges:!0,topOnDOMChanges:!1,hScrollbar:h,vScrollbar:h,fadeScrollbar:j||!f,shrinkScrollbar:j||
!f,desktopCompatibility:!1,overflow:"auto",snap:!1,bounceLock:!1,scrollbarColor:"rgba(0,0,0,0.5)",onScrollEnd:function(){}};if("object"==typeof c)for(d in c)this.options[d]=c[d];if(this.options.desktopCompatibility)this.options.overflow="hidden";this.onScrollEnd=this.options.onScrollEnd;delete this.options.onScrollEnd;this.wrapper.style.overflow=this.options.overflow;this.refresh();window.addEventListener("onorientationchange"in window?"orientationchange":"resize",this,!1);if(f||this.options.desktopCompatibility)this.element.addEventListener(i,
this,!1),this.element.addEventListener(l,this,!1),this.element.addEventListener(n,this,!1);this.options.checkDOMChanges&&this.element.addEventListener("DOMSubtreeModified",this,!1)}function k(b,c,d,f,h){var i=document;this.dir=b;this.fade=d;this.shrink=f;this.uid=++m;this.bar=i.createElement("div");this.bar.style.cssText="position:absolute;top:0;left:0;-webkit-transition-timing-function:cubic-bezier(0,0,0.25,1);pointer-events:none;-webkit-transition-duration:0;-webkit-transition-delay:0;-webkit-transition-property:-webkit-transform;z-index:10;background:"+
h+";-webkit-transform:"+o+"0,0"+p+";"+("horizontal"==b?"-webkit-border-radius:3px 2px;min-width:6px;min-height:5px":"-webkit-border-radius:2px 3px;min-width:5px;min-height:6px");this.wrapper=i.createElement("div");this.wrapper.style.cssText="-webkit-mask:-webkit-canvas(scrollbar"+this.uid+this.dir+");position:absolute;z-index:10;pointer-events:none;overflow:hidden;opacity:0;-webkit-transition-duration:"+(d?"300ms":"0")+";-webkit-transition-delay:0;-webkit-transition-property:opacity;"+("horizontal"==
this.dir?"bottom:2px;left:2px;right:7px;height:5px":"top:2px;right:2px;bottom:7px;width:5px;");this.wrapper.appendChild(this.bar);c.appendChild(this.wrapper)}d.prototype={x:0,y:0,enabled:!0,handleEvent:function(b){switch(b.type){case i:this.touchStart(b);break;case l:this.touchMove(b);break;case n:this.touchEnd(b);break;case "webkitTransitionEnd":this.transitionEnd();break;case "orientationchange":case "resize":this.refresh();break;case "DOMSubtreeModified":this.onDOMModified(b)}},onDOMModified:function(b){var c=
this;b.target.parentNode==c.element&&(setTimeout(function(){c.refresh()},0),c.options.topOnDOMChanges&&(0!=c.x||0!=c.y)&&c.scrollTo(0,0,"0"))},refresh:function(){var b=this.x,c=this.y;this.scrollWidth=this.wrapper.clientWidth;this.scrollHeight=this.wrapper.clientHeight;this.scrollerWidth=this.element.offsetWidth;this.scrollerHeight=this.element.offsetHeight;this.maxScrollX=this.scrollWidth-this.scrollerWidth;this.maxScrollY=this.scrollHeight-this.scrollerHeight;this.directionY=this.directionX=0;if(this.scrollX)if(0<=
this.maxScrollX)b=0;else if(this.x<this.maxScrollX)b=this.maxScrollX;if(this.scrollY)if(0<=this.maxScrollY)c=0;else if(this.y<this.maxScrollY)c=this.maxScrollY;if(this.options.snap)this.maxPageX=-Math.floor(this.maxScrollX/this.scrollWidth),this.maxPageY=-Math.floor(this.maxScrollY/this.scrollHeight),c=this.snap(b,c),b=c.x,c=c.y;if(b!=this.x||c!=this.y)this.setTransitionTime("0"),this.setPosition(b,c,!0);this.scrollX=this.scrollerWidth>this.scrollWidth;this.scrollY=!this.options.bounceLock&&!this.scrollX||
this.scrollerHeight>this.scrollHeight;if(this.options.hScrollbar&&this.scrollX)this.scrollBarX=this.scrollBarX||new k("horizontal",this.wrapper,this.options.fadeScrollbar,this.options.shrinkScrollbar,this.options.scrollbarColor),this.scrollBarX.init(this.scrollWidth,this.scrollerWidth);else if(this.scrollBarX)this.scrollBarX=this.scrollBarX.remove();if(this.options.vScrollbar&&this.scrollY&&this.scrollerHeight>this.scrollHeight)this.scrollBarY=this.scrollBarY||new k("vertical",this.wrapper,this.options.fadeScrollbar,
this.options.shrinkScrollbar,this.options.scrollbarColor),this.scrollBarY.init(this.scrollHeight,this.scrollerHeight);else if(this.scrollBarY)this.scrollBarY=this.scrollBarY.remove()},setPosition:function(b,c,d){this.x=b;this.y=c;this.element.style.webkitTransform=o+this.x+"px,"+this.y+"px"+p;d||(this.scrollBarX&&this.scrollBarX.setPosition(this.x),this.scrollBarY&&this.scrollBarY.setPosition(this.y))},setTransitionTime:function(b){b=b||"0";this.element.style.webkitTransitionDuration=b;if(this.scrollBarX)this.scrollBarX.bar.style.webkitTransitionDuration=
b,this.scrollBarX.wrapper.style.webkitTransitionDuration=h&&this.options.fadeScrollbar?"300ms":"0";if(this.scrollBarY)this.scrollBarY.bar.style.webkitTransitionDuration=b,this.scrollBarY.wrapper.style.webkitTransitionDuration=h&&this.options.fadeScrollbar?"300ms":"0"},touchStart:function(b){var c;if(this.enabled){this.scrolling=!0;this.moved=!1;this.distY=this.distX=0;this.setTransitionTime("0");if(this.options.momentum||this.options.snap)if(c=new WebKitCSSMatrix(window.getComputedStyle(this.element).webkitTransform),
c.e!=this.x||c.f!=this.y)document.removeEventListener("webkitTransitionEnd",this,!1),this.setPosition(c.e,c.f),this.moved=!0;this.touchStartX=f?b.changedTouches[0].pageX:b.pageX;this.scrollStartX=this.x;this.touchStartY=f?b.changedTouches[0].pageY:b.pageY;this.scrollStartY=this.y;this.scrollStartTime=b.timeStamp;this.directionY=this.directionX=0}},touchMove:function(b){if(this.scrolling){var c=f?b.changedTouches[0].pageX:b.pageX,b=f?b.changedTouches[0].pageY:b.pageY,d=this.scrollX?c-this.touchStartX:
0,h=this.scrollY?b-this.touchStartY:0,i=this.x+d,j=this.y+h;this.touchStartX=c;this.touchStartY=b;if(0<=i||i<this.maxScrollX)i=this.options.bounce?Math.round(this.x+d/3):0<=i||0<=this.maxScrollX?0:this.maxScrollX;if(0<=j||j<this.maxScrollY)j=this.options.bounce?Math.round(this.y+h/3):0<=j||0<=this.maxScrollY?0:this.maxScrollY;if(5<this.distX+this.distY){if(this.distX-3>this.distY)j=this.y,h=0;else if(this.distY-3>this.distX)i=this.x,d=0;this.setPosition(i,j);this.moved=!0;this.directionX=0<d?-1:1;
this.directionY=0<h?-1:1}else this.distX+=Math.abs(d),this.distY+=Math.abs(h)}},touchEnd:function(b){if(this.scrolling){var c=b.timeStamp-this.scrollStartTime,d=f?b.changedTouches[0]:b,h,i;h=0;i=this.x;var j=this.y;this.scrolling=!1;if(this.moved)if(!this.options.snap&&250<c)this.resetPosition();else{this.options.momentum&&(b=!0===this.scrollX?this.momentum(this.x-this.scrollStartX,c,this.options.bounce?-this.x+this.scrollWidth/5:-this.x,this.options.bounce?this.x+this.scrollerWidth-this.scrollWidth+
this.scrollWidth/5:this.x+this.scrollerWidth-this.scrollWidth):{dist:0,time:0},d=!0===this.scrollY?this.momentum(this.y-this.scrollStartY,c,this.options.bounce?-this.y+this.scrollHeight/5:-this.y,this.options.bounce?(0>this.maxScrollY?this.y+this.scrollerHeight-this.scrollHeight:0)+this.scrollHeight/5:this.y+this.scrollerHeight-this.scrollHeight):{dist:0,time:0},h=Math.max(Math.max(b.time,d.time),1),i=this.x+b.dist,j=this.y+d.dist);if(this.options.snap)b=this.snap(i,j),i=b.x,j=b.y,h=Math.max(b.time,
h);this.scrollTo(i,j,h+"ms")}else if(this.resetPosition(),f){for(h=d.target;1!=h.nodeType;)h=h.parentNode;i=document.createEvent("MouseEvents");i.initMouseEvent("click",!0,!0,b.view,1,d.screenX,d.screenY,d.clientX,d.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,0,null);i._fake=!0;h.dispatchEvent(i)}}},transitionEnd:function(){document.removeEventListener("webkitTransitionEnd",this,!1);this.resetPosition()},resetPosition:function(){var b=this.x,c=this.y;if(0<=this.x)b=0;else if(this.x<this.maxScrollX)b=
this.maxScrollX;if(0<=this.y||0<this.maxScrollY)c=0;else if(this.y<this.maxScrollY)c=this.maxScrollY;if(b!=this.x||c!=this.y)this.scrollTo(b,c);else{if(this.moved)this.onScrollEnd(),this.moved=!1;this.scrollBarX&&this.scrollBarX.hide();this.scrollBarY&&this.scrollBarY.hide()}},snap:function(b,c){var d,b=0<this.directionX?Math.floor(b/this.scrollWidth):0>this.directionX?Math.ceil(b/this.scrollWidth):Math.round(b/this.scrollWidth);this.pageX=-b;b*=this.scrollWidth;if(0<b)b=this.pageX=0;else if(b<this.maxScrollX)this.pageX=
this.maxPageX,b=this.maxScrollX;c=0<this.directionY?Math.floor(c/this.scrollHeight):0>this.directionY?Math.ceil(c/this.scrollHeight):Math.round(c/this.scrollHeight);this.pageY=-c;c*=this.scrollHeight;if(0<c)c=this.pageY=0;else if(c<this.maxScrollY)this.pageY=this.maxPageY,c=this.maxScrollY;d=Math.round(Math.max(500*(Math.abs(this.x-b)/this.scrollWidth),500*(Math.abs(this.y-c)/this.scrollHeight)));return{x:b,y:c,time:d}},scrollTo:function(b,c,d){this.x==b&&this.y==c?this.resetPosition():(this.moved=
!0,this.setTransitionTime(d||"350ms"),this.setPosition(b,c),"0"===d||"0s"==d||"0ms"==d?this.resetPosition():document.addEventListener("webkitTransitionEnd",this,!1))},scrollToPage:function(b,c,d){if(!this.options.snap)this.pageX=-Math.round(this.x/this.scrollWidth),this.pageY=-Math.round(this.y/this.scrollHeight);"next"==b?b=++this.pageX:"prev"==b&&(b=--this.pageX);"next"==c?c=++this.pageY:"prev"==c&&(c=--this.pageY);b=-b*this.scrollWidth;c=-c*this.scrollHeight;c=this.snap(b,c);b=c.x;c=c.y;this.scrollTo(b,
c,d||"500ms")},scrollToElement:function(b,c){if(b="object"==typeof b?b:this.element.querySelector(b)){var d=this.scrollX?-b.offsetLeft:0,f=this.scrollY?-b.offsetTop:0;if(0<=d)d=0;else if(d<this.maxScrollX)d=this.maxScrollX;if(0<=f)f=0;else if(f<this.maxScrollY)f=this.maxScrollY;this.scrollTo(d,f,c)}},momentum:function(b,c,d,f){var c=1E3*(Math.abs(b)/c),h=c*c/2.5/1E3,i=0;0<b&&h>d?(c=c*d/h/2.5,h=d):0>b&&h>f&&(c=c*f/h/2.5,h=f);i=c/1.2;return{dist:Math.round(h*(0>b?-1:1)),time:Math.round(i)}},destroy:function(b){window.removeEventListener("onorientationchange"in
window?"orientationchange":"resize",this,!1);this.element.removeEventListener(i,this,!1);this.element.removeEventListener(l,this,!1);this.element.removeEventListener(n,this,!1);document.removeEventListener("webkitTransitionEnd",this,!1);this.options.checkDOMChanges&&this.element.removeEventListener("DOMSubtreeModified",this,!1);if(this.scrollBarX)this.scrollBarX=this.scrollBarX.remove();if(this.scrollBarY)this.scrollBarY=this.scrollBarY.remove();b&&this.wrapper.parentNode.removeChild(this.wrapper);
return null}};k.prototype={init:function(b,c){var d=document,f=Math.PI;if("horizontal"==this.dir){if(this.maxSize!=this.wrapper.offsetWidth)this.maxSize=this.wrapper.offsetWidth,d=d.getCSSCanvasContext("2d","scrollbar"+this.uid+this.dir,this.maxSize,5),d.fillStyle="rgb(0,0,0)",d.beginPath(),d.arc(2.5,2.5,2.5,f/2,-f/2,!1),d.lineTo(this.maxSize-2.5,0),d.arc(this.maxSize-2.5,2.5,2.5,-f/2,f/2,!1),d.closePath(),d.fill()}else if(this.maxSize!=this.wrapper.offsetHeight)this.maxSize=this.wrapper.offsetHeight,
d=d.getCSSCanvasContext("2d","scrollbar"+this.uid+this.dir,5,this.maxSize),d.fillStyle="rgb(0,0,0)",d.beginPath(),d.arc(2.5,2.5,2.5,f,0,!1),d.lineTo(5,this.maxSize-2.5),d.arc(2.5,this.maxSize-2.5,2.5,0,f,!1),d.closePath(),d.fill();this.size=Math.max(Math.round(this.maxSize*this.maxSize/c),6);this.maxScroll=this.maxSize-this.size;this.toWrapperProp=this.maxScroll/(b-c);this.bar.style["horizontal"==this.dir?"width":"height"]=this.size+"px"},setPosition:function(b){"1"!=this.wrapper.style.opacity&&this.show();
b=Math.round(this.toWrapperProp*b);0>b?(b=this.shrink?b+3*b:0,7>this.size+b&&(b=-this.size+6)):b>this.maxScroll&&(b=this.shrink?b+3*(b-this.maxScroll):this.maxScroll,7>this.size+this.maxScroll-b&&(b=this.size+this.maxScroll-6));b="horizontal"==this.dir?o+b+"px,0"+p:o+"0,"+b+"px"+p;this.bar.style.webkitTransform=b},show:function(){if(h)this.wrapper.style.webkitTransitionDelay="0";this.wrapper.style.opacity="1"},hide:function(){if(h)this.wrapper.style.webkitTransitionDelay="350ms";this.wrapper.style.opacity=
"0"},remove:function(){null!=this.wrapper.parentNode&&this.wrapper.parentNode.removeChild(this.wrapper);return null}};var h="WebKitCSSMatrix"in window&&"m11"in new WebKitCSSMatrix,j=/iphone|ipad/gi.test(navigator.appVersion),f="ontouchstart"in window,i=f?"touchstart":"mousedown",l=f?"touchmove":"mousemove",n=f?"touchend":"mouseup",o="translate"+(h?"3d(":"("),p=h?",0)":")",m=0;window.iScroll=d})();ucf.CacheProvider=ucf.CacheProvider||function(){this.cache={};this._keyPrefix="ucf_"};
var loadProvider=function(){(function(d){try{d.hasLocalStorage="localStorage"in window&&null!==window.localStorage}catch(k){d.hasLocalStorage=!1}if(d.hasLocalStorage)d.prototype.storage=window.localStorage;var h=d.prototype.storage;d.prototype.get=function(j,f){if(f&&d.hasLocalStorage){if(h!==window.localStorage)h=window.localStorage;var i=h.getItem(this._keyPrefix+j);return i?JSON.parse(i):void 0}return this.cache[j]||void 0};d.prototype.set=function(j,f,i){if(i&&d.hasLocalStorage){if(h!==window.localStorage)h=
window.localStorage;h.setItem(this._keyPrefix+j,JSON.stringify(f))}else this.cache[j]=f;return f};d.prototype.remove=function(j,f){f&&d.hasLocalStorage&&h.removeItem(this._keyPrefix+j);delete this.cache[j]}})(ucf.CacheProvider)};document.addEventListener("bridgeready",loadProvider);loadProvider();ucf.Cache=ucf.Cache||{};
(function(d){var k=null,h=0,j={gcFreq:60};d.init=function(){k=k||new ucf.CacheProvider};d.setup=function(d){_.extend(j,d)};d.set=function(f,i,o,p){d.init();_.isNumber(o)&&1<=o&&(i={expire:Math.ceil((new Date).getTime()/1E3)+o,val:i});k.set(f,i,p);h||(h=setInterval(d.gc,j.gcFreq));return this};d.get=function(f,h){d.init();var i=k.get(f,h);if(!_.isUndefined(i)&&!_.isUndefined(i.expire)&&!_.isNull(i.expire)){var j=Math.ceil((new Date).getTime()/1E3);1<=i.expire-j?i=i.val:(k.remove(f,h),i=void 0)}return i};
d.remove=function(f,h){d.init();k.remove(f,h);return this};var f=function(){var f=k.cache,h;for(h in f)_.isUndefined(h)||d.get(h,!1);return this},i=function(){var f=k.storage;if(!_.isEmpty(f)){for(var h=f.length,i=0;i<h;i++)d.get(f.key(i),!0);return this}};d.gc=function(){f();i();return this}})(ucf.Cache);ucf.Date=ucf.Date||{};
(function(d){d.strToDate=function(d){return new Date(Date.parse(d.replace(/-/g,"/")))};d.timeToDate=function(d){return new Date(1E3*d)};d.formatDate=function(d,h){"string"==typeof d&&(d=this.strToDate(d));if(d instanceof Date){var j=d.getFullYear(),f=d.getMonth()+1,i=d.getDate(),l=d.getHours(),n=d.getMinutes(),o=d.getSeconds(),p=d.getMilliseconds();return h&&0<p?j+"-"+f+"-"+i+" "+l+":"+n+":"+o+"."+p:0<l||0<n||0<o?j+"-"+f+"-"+i+" "+l+":"+n+":"+o:j+"-"+f+"-"+i}return""};d.compareTime=function(d,h){var j=
d.split("-"),f=h.split("-");return parseInt(j[0])>parseInt(f[0])?1:parseInt(j[0])<parseInt(f[0])?-1:parseInt(j[1])>parseInt(f[1])?1:parseInt(j[1])<parseInt(f[1])?-1:parseInt(j[2])>parseInt(f[2])?1:parseInt(j[2])<parseInt(f[2])?-1:0}})(ucf.Date);ucf.effect.Touch=ucf.effect.Touch||{};
(function(d){d.events=[];d.isTouchDevice=function(){try{return document.createEvent("TouchEvent"),!0}catch(d){return!1}};d.on=function(k,h,j,f,i,l,n){var f=null!=f?f:!0,o="",p="",m="",i=!_.isUndefined(i)?i:{};switch(k){case "start":o="mousedown";p="touchstart";break;case "move":o="mousemove";p="touchmove";break;case "up":o="mouseup",p="touchend"}m=d.isTouchDevice()?p:o;!_.isUndefined(l)&&!_.isEmpty(l)&&(m+=l);if(!_.isUndefined(n)&&!_.isEmpty(n))$(h).on(m,n,function(b){f&&b.preventDefault();j(b.originalEvent?
b.originalEvent:b,this,i)});else $(h).on(m,function(b){f&&b.preventDefault();j(b.originalEvent?b.originalEvent:b,this,i)})};d.off=function(d,h,j){var f="",i="";switch(d){case "start":f="mousedown";i="touchstart";break;case "move":f="mousemove";i="touchmove";break;case "up":f="mouseup";i="touchend";break;case "click":f=["mousedown","mousemove","mouseup","click"];i=["touchstart","touchmove","touchend"];break;default:i=f=""}!_.isUndefined(j)&&!_.isEmpty(j)&&(_.isArray(f)?_.each(f,function(d,h){f[h]=
d+j}):f+=j,_.isArray(i)?_.each(i,function(d,f){i[f]=d+j}):i+=j);_.isArray(f)?_.each(f,function(d){$(h).off(d)}):$(h).off(f);_.isArray(i)?_.each(i,function(d){$(h).off(d)}):$(h).off(i)}})(ucf.effect.Touch);ucf.utils.Body=ucf.utils.Body||{};
(function(d){d.layout="north,south,west,east,northwest,southwest,northeast,southeast,center".split(",");d.getPageSize=function(){var d=document.body.offsetWidth,h=document.body.offsetHeight,j=document.body.clientWidth,f=self.innerHeight;return[d<j?d:j,h<f?f:h,j,f]};d.getPageScroll=function(){return[self.pageXOffset,self.pageYOffset]};d.getPosition=function(k,h,j){var k=0<k?k:0,h=0<h?h:0,f=d.getPageSize(),i=d.getPageScroll(),l=0,n=0,o=f[2]/3,f=f[3]/3,p=0,m=0,b=0,c=0;k!=o&&(l=(o-k)/2);h!=f&&(n=(f-h)/
2);j=j||"center";0<=j.indexOf("north")?0>n?(m=i[1],c=0):(m=i[1]+n,c=n):0<=j.indexOf("south")?0>n?(m=i[1]+2*f+2*n,c=2*f+2*n):(m=i[1]+2*f+n,c=2*f+n):(m=i[1]+f+n,c=f+n);0<=j.indexOf("east")?0>l?(p=i[0]+2*o+2*l,b=2*o+2*l):(p=i[0]+2*o+l,b=2*o+l):0<=j.indexOf("west")?0>l?(p=i[0],b=0):(p=i[0]+l,b=l):(p=i[0]+o+l,b=o+l);return[Math.round(p),Math.round(m),Math.round(b),Math.round(c)]}})(ucf.utils.Body);(function(d){d.fn.UcEffects=function(){function k(d){var f=new Date;do var h=new Date;while(h-f<d)}var h=this;h.specialShow=function(j,f,i,l){var n=parseInt(h.width()),o=parseInt(h.height()),p=d(this);_.each({paddingLeft:{type:"width",count:1},paddingRight:{type:"width",count:1},paddingTop:{type:"height",count:1},paddingBottom:{type:"height",count:1},border:{count:2}},function(b,c){b.value=parseInt(p.css(c));b.value=!isNaN(b.value)?b.value:0;"width"==b.type?n+=b.value*b.count:("height"!=b.type&&(n+=
b.value*b.count),o+=b.value*b.count)});h.hide();h.css("overflow","hidden");var m,b,c,r={},s=ucf.utils.Body.getPageScroll();_.isString(j)?(0>_.indexOf(ucf.utils.Body.layout,j)&&(j="west"),m=ucf.utils.Body.getPosition(n,o,j),b=m[2]+s[0],c=m[3]+s[1]):_.isEmpty(j)||(m=ucf.utils.Body.getPosition(n,o,"west"),c=!_.isUndefined(j.top)&&0<=j.top?j.top:m[3],b=!_.isUndefined(j.left)&&0<=j.left?j.left:m[2],b+=s[0],c+=s[1]);if(_.isString(f))0>_.indexOf(ucf.utils.Body.layout,f)&&(f="center"),m=ucf.utils.Body.getPosition(n,
o,f),r.left=m[2]+s[0],r.top=m[3]+s[1];else if(!_.isEmpty(f))m=ucf.utils.Body.getPosition(n,o,"center"),r.top=!_.isUndefined(f.top)&&0<=f.top?f.top:m[3],r.left=!_.isUndefined(f.left)&&0<=f.left?f.left:m[2],r.left+=s[0],r.top+=s[1];i=null!=i?i:!1;h.show();if(i)h.css("width",0),h.css("height",0),r.width=n,r.height=o,k(100);h.css("position","absolute");console.log(s);b==r.left&&c==r.top?i&&(h.css("left",r.left+Math.ceil(n/2)),h.css("top",r.top+Math.ceil(o/2))):(h.css("left",b),h.css("top",c));console.log(r);
h.animate(r,100,"linear",function(){h.css({overflow:""});!_.isFunction(l)||l()})};h.moveTo=function(j,f){var i={paddingLeft:{type:"width",count:1},paddingRight:{type:"width",count:1},paddingTop:{type:"height",count:1},paddingBottom:{type:"height",count:1},border:{count:2}},k=parseInt(h.width()),n=parseInt(h.height()),o=d(this);_.each(i,function(b,c){b.value=parseInt(o.css(c));b.value=!isNaN(b.value)?b.value:0;"width"==b.type?k+=b.value*b.count:("height"!=b.type&&(k+=b.value*b.count),n+=b.value*b.count)});
if(0<h.length){var p={},m=ucf.utils.Body.getPageScroll();if(0<=_.indexOf(ucf.utils.Body.layout,j))i={paddingLeft:{type:"width",count:1},paddingRight:{type:"width",count:1},paddingTop:{type:"height",count:1},paddingBottom:{type:"height",count:1},border:{count:2}},k=parseInt(h.width()),n=parseInt(h.height()),_.each(i,function(b,c){b.value=parseInt(h.css(c));b.value=!isNaN(b.value)?b.value:0;"width"==b.type?k+=b.value*b.count:("height"!=b.type&&(k+=b.value*b.count),n+=b.value*b.count)}),i=ucf.utils.Body.getPosition(k,
n,j),p.left=i[2]+m[0],p.top=i[3]+m[1];else{if(j&&h.css("left")!=j)p.left=j+m[0];if(f&&h.css("top")!=f)p.top=f+m[1]}p.width=k;p.height=n;p.position="absolute";_.isEmpty(p)||h.css(p)}};return h}})($);
